// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwgmrqizyovwvwbyapqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3Z21ycWl6eW92d3Z3YnlhcHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDMwNjYsImV4cCI6MjA1OTMxOTA2Nn0.QCOPzdwEMCQW0gCqi7g8mGgK3gn9TEC8VJz-mY29QPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);